- name: Deploy go app
  hosts: all
  roles:
    - name: "Deploy kolay0ne/app_go:lab6"
      role: web_app
      image_name: "kolay0ne/app_go"
      image_tag: "lab6"
      publish_ports:
        - "5500:5000"
      wipe: false
      tags: []  # Run by default

    - name: "Wipe kolay0ne/app_go:lab6"
      role: web_app
      image_name: "kolay0ne/app_go"
      image_tag: "lab6"
      wipe: true
      tags: [never, wipe]  # Only run on wipe
