global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: app_py
    static_configs:
      - targets: ['app_py:5000']

  - job_name: app_go
    static_configs:
      - targets: ['app_go:5000']
