server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "warn"

positions:
  filename: /var/lib/promtail/positions/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - regex:
          source: filename
          expression: "^/var/lib/docker/containers/(?P<container_id>[0-9a-f]{64})/[0-9a-f]{64}-json.log"
      - labels:
          container_id:
      - docker:
      - decolorize:
