- name: Fail if not debian-based
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'
  shell: echo 'This role only works for Ubuntu or Debian'; false

- include_tasks: docker.yaml

- include_tasks: docker-compose.yaml
